create table if not exists conversations (
    id bigint generated by default as identity primary key,
    phone_number text not null unique,
    customer_name text default '',
    last_message text default '',
    last_message_time timestamptz default now(),
    unread_count integer not null default 0,
    status text not null default 'open',
    created_at timestamptz not null default now()
);

create table if not exists messages (
    id bigint generated by default as identity primary key,
    conversation_id bigint not null references conversations(id) on delete cascade,
    phone_number text default '',
    direction text not null check (direction in ('inbound', 'outbound')),
    body text default '',
    message_sid text,
    status text default '',
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists messages_conversation_created_idx
    on messages(conversation_id, created_at);

create index if not exists messages_sid_idx
    on messages(message_sid);

